### PR TITLE
Padding issue on navbar and Task on Create Gate

### PR DESCRIPTION
**Pull request by Ashishgy**
# [PR Name]

## Type of PR

Bug FIX 

## Checklist

- [] - Provided useful description for this PR
- [] - Provided the root cause of this bugfix
- [] - Tested on supported devices

### CODE REVIEW

**Review by NunoMartins21 — CHANGES_REQUESTED** [review]
I can't approve this at the moment. There's a merge conflict on `create-gate.tsx` and the `schema.ts` for the create-gate template is referencing work from another branch which is not committed yet.

I need you to fix these things first. And also, please do be careful with the files (regarding we having here work from the other PR). You should make sure your working tree is clear (this is, without files belonging to another PR) before you start working on another feature/branch. I'd recommend using `git stash` in these situations. Lmk if you have any questions!

**Review by fbenfraj — APPROVED** [review]

**Review by fbenfraj — COMMENTED** [review]
Changes lgtm but fix conflicts

**Comment by Ashishgy** [comment]
@NunoMartins21 I can see that as of now, But when I push this thing few days back , there were no merge conflict, May be now it has come because of Draft Gate part. 

Yes my working stree is clear. It is probably because of Faruk's Draft Gate portion push

**Comment by Ashishgy** [comment]
I will make the changes and see the conflicts soon ! @NunoMartins21

**Pull request closed without merging**
